src/Entity/EC.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Expr\Cast\String_;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ECRepository")
 * @ORM\Table(name="ec")
 */
class EC
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champ obligatoire")
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UC", inversedBy="eCs",cascade={"persist"}))
     */
    private $UC;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="EC")
     */
    private $notes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FicheIndividuel", mappedBy="EC")
     */
    private $ficheIndividuels;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RepartitionEC", mappedBy="ec", cascade={"persist"})
     */
    private $repartitionECs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EmploiDuTemps", mappedBy="ec")
     */
    private $emploiDuTemps;

    /**
     * @ORM\Column(type="float")
     */
    private $coefficient;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champ obligatoire")
     */
    private $code;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Champ obligatoire")
     */
    private $credit;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Enseignant", inversedBy="eCs")
     */
    private $enseignant;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Niveaux", inversedBy="eCs")
     */
    private $niveaux;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Semestre", inversedBy="eCs")
     */
    private $semestres;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
        $this->ficheIndividuels = new ArrayCollection();
        $this->repartitionECs = new ArrayCollection();
        $this->emploiDuTemps = new ArrayCollection();
        $this->niveaux = new ArrayCollection();
        $this->semestres = new ArrayCollection();
    }

    public function getEnseignant(): ?Enseignant
    {
        return $this->enseignant;
    }

    public function setEnseignant(?Enseignant $enseignant): self
    {
        $this->enseignant = $enseignant;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCoefficient(): ?float
    {
        return $this->coefficient;
    }

    public function setCoefficient(float $coefficient): self
    {
        $this->coefficient = $coefficient;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getCredit(): ?int
    {
        return $this->credit;
    }

    public function setCredit(int $credit): self
    {
        $this->credit = $credit;

        return $this;
    }

    public function getUC(): ?UC
    {
        return $this->UC;
    }

    public function setUC(?UC $UC): self
    {
        $this->UC = $UC;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setEC($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getEC() === $this) {
                $note->setEC(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FicheIndividuel[]
     */
    public function getFicheIndividuels(): Collection
    {
        return $this->ficheIndividuels;
    }

    public function addFicheIndividuel(FicheIndividuel $ficheIndividuel): self
    {
        if (!$this->ficheIndividuels->contains($ficheIndividuel)) {
            $this->ficheIndividuels[] = $ficheIndividuel;
            $ficheIndividuel->setEC($this);
        }

        return $this;
    }

    public function removeFicheIndividuel(FicheIndividuel $ficheIndividuel): self
    {
        if ($this->ficheIndividuels->contains($ficheIndividuel)) {
            $this->ficheIndividuels->removeElement($ficheIndividuel);
            // set the owning side to null (unless already changed)
            if ($ficheIndividuel->getEC() === $this) {
                $ficheIndividuel->setEC(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RepartitionEC[]
     */
    public function getRepartitionECs(): Collection
    {
        return $this->repartitionECs;
    }

    public function addRepartitionEC(RepartitionEC $repartitionEC): self
    {
        if (!$this->repartitionECs->contains($repartitionEC)) {
            $this->repartitionECs[] = $repartitionEC;
            $repartitionEC->setEc($this);
        }

        return $this;
    }

    public function removeRepartitionEC(RepartitionEC $repartitionEC): self
    {
        if ($this->repartitionECs->contains($repartitionEC)) {
            $this->repartitionECs->removeElement($repartitionEC);
            // set the owning side to null (unless already changed)
            if ($repartitionEC->getEc() === $this) {
                $repartitionEC->setEc(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EmploiDuTemps[]
     */
    public function getEmploiDuTemps(): Collection
    {
        return $this->emploiDuTemps;
    }

    public function addEmploiDuTemp(EmploiDuTemps $emploiDuTemp): self
    {
        if (!$this->emploiDuTemps->contains($emploiDuTemp)) {
            $this->emploiDuTemps[] = $emploiDuTemp;
            $emploiDuTemp->setEc($this);
        }

        return $this;
    }

    public function removeEmploiDuTemp(EmploiDuTemps $emploiDuTemp): self
    {
        if ($this->emploiDuTemps->contains($emploiDuTemp)) {
            $this->emploiDuTemps->removeElement($emploiDuTemp);
            // set the owning side to null (unless already changed)
            if ($emploiDuTemp->getEc() === $this) {
                $emploiDuTemp->setEc(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNiveau(): ?Niveaux
    {
        return $this->niveau;
    }

    public function setNiveau(?Niveaux $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getSemestre(): ?Semestre
    {
        return $this->semestre;
    }

    public function setSemestre(?Semestre $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }

    /**
     * @return Collection|Niveaux[]
     */
    public function getNiveaux(): Collection
    {
        return $this->niveaux;
    }

    public function addNiveau(Niveaux $niveau): self
    {
        if (!$this->niveaux->contains($niveau)) {
            $this->niveaux[] = $niveau;
        }

        return $this;
    }

    public function removeNiveau(Niveaux $niveau): self
    {
        if ($this->niveaux->contains($niveau)) {
            $this->niveaux->removeElement($niveau);
        }

        return $this;
    }

    /**
     * @return Collection|Semestre[]
     */
    public function getSemestres(): Collection
    {
        return $this->semestres;
    }

    public function addSemestre(Semestre $semestre): self
    {
        if (!$this->semestres->contains($semestre)) {
            $this->semestres[] = $semestre;
        }

        return $this;
    }

    public function removeSemestre(Semestre $semestre): self
    {
        if ($this->semestres->contains($semestre)) {
            $this->semestres->removeElement($semestre);
        }

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

}
 

src/Controller/UCController.php
<?php

namespace App\Controller;

use App\Entity\UC;
use App\Form\UCType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\TypeParcours;
use App\Entity\Niveaux;
use App\Entity\Semestre;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class UCController extends AbstractController
{
    /**
     * @Route("/u/c/ajoute", name="add_u_c")
     * 
     * Require ROLE_ADMIN for only this controller method.
     * 
     *  @IsGranted("ROLE_ADMIN")
     */
    public function index(Request $request)
    {
        $status = 'addUc';

        $uc = new UC();
        $form = $this->createForm(UCType::class, $uc);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $typeRep = $em->getRepository(TypeParcours::class);
            $type = $typeRep->findAll();
            $t = $type['0']->getId();
            $uc2 = new UC();
            foreach($uc->getNiveaux() as $value)
            {
                $niveaux[]=$value['niveaux'];
                $semestre[]=$value['semestre'];
            }
            $uc2 = new UC();
            foreach($niveaux as $niveau)
            {
                $uc2->addNiveau($niveau);
            }
            foreach($semestre as $sem )
            {
                $uc2->addSemestre($sem);
            }
            $uc2->setCoefficient(1);
            $uc2->setCredit($uc->getCredit());
            $uc2->setNom($uc->getNom());
            $em->persist($uc2);
            $em->flush();
            return $this->redirectToRoute('repartition_uc_by_niveau_edit',['type'=>$t,'niveau'=>$niveaux['0']->getId()]);
        }

        return $this->render('uc/index.html.twig', ['status' => $status, 'form' => $form->createView()]);
    }

    /**
     * @Route("/u/c/edit/{id}", name="ue_edit")
     * 
     * Require ROLE_ADMIN for only this controller method.
     * 
     *  @IsGranted("ROLE_ADMIN")
     */
    public function edit_ue(Request $request,UC $uc)
    {
        $status = 'editUe';
        $form = $this->createForm(UCType::class, $uc);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $typeRep = $em->getRepository(TypeParcours::class);
            $type = $typeRep->findAll();
            $t = $type['0']->getId();

            // foreach($uc->getNiveaux() as $value)
            // {
            //     $niveaux[]=$value['niveaux'];
            //     $semestre[]=$value['semestre'];
            // }
            // $uc2 = new UC();
            // foreach($niveaux as $niveau)
            // {
            //     $uc2->addNiveau($niveau);
            // }
            // foreach($semestre as $sem )
            // {
            //     $uc2->addSemestre($sem);
            // }
            // $uc2->setCoefficient($uc->getCoefficient());
            // $uc2->setCredit($uc->getCredit());
            // $uc2->setNom($uc->getNom());
             
            $em->persist($uc);
            $em->flush();
            return $this->redirectToRoute('repartition_uc_by_niveau_edit',['type'=>$t,'niveau'=>$uc->getNiveaux()['0']->getId()]);
        }

        return $this->render('uc/index.html.twig', ['status' => $status, 'form' => $form->createView()]);
    }

    /**
     * @Route("u/c/list" , name="ucList")
     * Vous n'avez pas le permission de voir cette page.
     *
     * @IsGranted("ROLE_USER")
     */
    public function list()
    {
        $status = 'UCEC';
        $em = $this->getDoctrine()->getManager();
        $ucRepository = $em->getRepository(UC::class);
        $uc = $ucRepository->findAllCustom();

        return $this->render('uc/list.html.twig', ['status' => $status, 'uc' => $uc]);
    }

    /**
     * @Route("uc/rep/list/{type}/{niveau}" , name="repartition_uc_by_niveau")
     * Vous n'avez pas le permission de voir cette page.
     *
     * @IsGranted("ROLE_USER")
     */
    public function repartition_uc_by_niveau($type, $niveau)
    {
        $status = 'r_u_b_n';
        $em = $this->getDoctrine()->getManager();
        $typeParcoursRepository = $em->getRepository(TypeParcours::class);
        $niveauxRepository = $em->getRepository(Niveaux::class);
        $semestreRepository = $em->getRepository(Semestre::class);

        $parcours = $typeParcoursRepository->find($type);
        $niv = $niveauxRepository->findByType($type);
        $semestre = $semestreRepository->findSemestreByNiveaux($niveau);
        
        return $this->render('uc/repartition_uc_by_niveau.html.twig', [
            'status' => $status,
            'parcour' => $parcours,
            'niveaux' => $niv,
            'n' => $niveau,
            'semestre' => $semestre
        ]);
    }

    /**
     * @Route("uc/rep/list-edit/{type}/{niveau}" , name="repartition_uc_by_niveau_edit")
     * Vous n'avez pas le permission de voir cette page.
     *
     * @IsGranted("ROLE_USER")
     */
    public function repartition_uc_by_niveau_edit($type, $niveau)
    {
        $status = 'r_u_b_n_edit';
        $em = $this->getDoctrine()->getManager();
        $typeParcoursRepository = $em->getRepository(TypeParcours::class);
        $niveauxRepository = $em->getRepository(Niveaux::class);
        $semestreRepository = $em->getRepository(Semestre::class);

        $parcours = $typeParcoursRepository->find($type);
        $niv = $niveauxRepository->findByType($type);
        $semestre = $semestreRepository->findSemestreByNiveaux($niveau);
        
        return $this->render('uc/repartition_uc_by_niveau_edit.html.twig', [
            'status' => $status,
            'parcour' => $parcours,
            'niveaux' => $niv,
            'n' => $niveau,
            'semestre' => $semestre
        ]);
    }

    /**
     * @Route("uc/rep/list/pdf/{type}/{niveau}" , name="repartition_uc_by_niveau_pdf")
     * Vous n'avez pas le permission de voir cette page.
     *
     * @IsGranted("ROLE_USER")
     */
    public function repartition_uc_by_niveau_pdf($type, $niveau)
    {
        $status = 'r_u_b_n';
        $em = $this->getDoctrine()->getManager();
        $typeParcoursRepository = $em->getRepository(TypeParcours::class);
        $niveauxRepository = $em->getRepository(Niveaux::class);
        $semestreRepository = $em->getRepository(Semestre::class);

        $niv_name = $niveauxRepository->find($niveau);
        $parcours = $typeParcoursRepository->find($type);
        $niv = $niveauxRepository->findByType($type);
        $semestre = $semestreRepository->findSemestreByNiveaux($niveau);
        
        return $this->render('uc/repartition_uc_by_niveau_pdf.html.twig', [
            'status' => $status,
            'parcour' => $parcours,
            'niveaux' => $niv,
            'n' => $niveau,
            'semestre' => $semestre,
            'niv_name' =>$niv_name
        ]);
    }
}

templates/uc/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter UE{% endblock %}

{% block insideHeader %}
    <section class="content-header">
        <h1>
            Ajouter UE
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Ajouter UE</a></li>
        </ol>
    </section>
{% endblock %}

{% block body %}
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Ajouter un UE</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            {{ form_start(form,{'attr':{'novalidate' : 'novalidate'}}) }}
            <div class="box-body">
                <div class="form-group">
                    {{ form_row(form.nom) }}
                    {# {{ form_row(form.coefficient) }}
                    {{ form_row(form.credit) }} #}
                    {{ form_row(form.niveaux) }}
                    {# {{ form_row(form.semestres) }} #}
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary pull-right">Valider</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
    <script src="{{asset('assets/js/ma6.js')}}"></script>
    <script>
        $(function () {
            SymfonyCollection.init({
                selector: '#uc_niveaux',
                label: 'niveau',
                add: {
                    content: 'Ajouter un niveau'
                },
                remove: {
                    content: 'supprimer un niveau',
                    attr: {
                        class: 'btn btn-link btn-sm'
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/uc/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des EC par enseignant{% endblock %}

{% block insideHeader %}
    <section class="content-header">
        <h1>
            Liste des EC par UE
            {#<small>{{ parcour.type }}</small>#}
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Liste des EC par UE</a></li>
            {#<li class="active">{{ parcour.type }}</li>#}
        </ol>
    </section>
{% endblock %}

{% block body %}
    <div class="row">
        {% for u in uc %}
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">{{ u.nom }}</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <table class="table table-striped">
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>EC</th>
                                <th>Enseignant</th>
                            </tr>
                            {% set i=0 %}
                            {% for EC in u.eCs %}
                                <tr>
                                    <td>{{ i }}</td>
                                    <td>{{ EC.nom }}</td>
                                    <td>
                                    {% for enseignant in EC.enseignant %}
                                        {{ enseignant.nom }}{{ '  ' }}{{ enseignant.prenom }}{{ ',' }}
                                    {% endfor %}
                                    </td>
                                </tr>
                                {% set i=i+1 %}
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        {% endfor %}
    </div>
    {#    {% for enseignant in enseignants %}
            <h1>{{ enseignant.nom }}</h1>
            {% for EC in enseignant.eCs %}
                {{ EC.nom }}
            {% endfor %}
        {% endfor %}#}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
{% endblock %}

templates/uc/repartition_uc_by_niveau.html.twig
{% extends 'base.html.twig' %}

{% block title %}Répartition des UE et EC
{% endblock %}

{% block insideHeader %}
    <section class="content-header">
        <h1>
            Répartition des UE et EC
            <small>{{ parcour.type }}</small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard"></i>Répartition des UE et EC</a>
            </li>
            <li class="active">{{ parcour.type }}</li>
        </ol>
    </section>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    {% for niveau in niveaux %}
                        <li class="{% if niveau.id == n %}{{ 'active' }}{% endif %}">
                            <a href="{{ path('repartition_uc_by_niveau',{'type':parcour.id,'niveau':niveau.id}) }}">{{ niveau.nom }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <div class="box-header">
                    <h3 class="box-title col-md-4"></h3>
                    <a href="{{path('repartition_uc_by_niveau_pdf',{'type':parcour.id,'niveau':n})}}" class="pull-right btn  btn-social btn-flickr">
                        <i class="fa fa-file-pdf-o"></i>
                        Générer un PDF
                    </a>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_1">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="nav-tabs-custom">
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab_1">
                                            <div class="col-md-12">
                                                <div class="nav-tabs-custom">
                                                    <div class="tab-content">
                                                        <div class="tab-pane active" id="tab_1-1">
                                                            <div class="row">
                                                                <div class="col-xs-12">
                                                                    <div class="box" style="background-color: #fff;overflow-y:scroll;">
                                                                        {% for sem in semestre %}
                                                                            <div class="box-body col-lg-6 col-md-6 col-xs-12">
                                                                                <h3 class="text-muted text-center">{{ sem.semestre }}</h3>
                                                                                <table class="table table-bordered table-striped" id="example1">
                                                                                    {% for ue in sem.uEs %}
                                                                                        <thead class="col-sm-offset-8">
                                                                                            <tr>
                                                                                                <th>{{ue.nom}} </th>
                                                                                                <th>{{ue.credit}} crédits</th>
                                                                                            </tr>
                                                                                        </thead>
                                                                                        <tbody>
                                                                                            {% for ec in ue.ecs %}
                                                                                            {% if ec.isActive == 1 %}                                                        
                                                                                                <tr>
                                                                                                    <td>{{ ec.nom }}</td>
                                                                                                    <td>{{ ec.code }}</td>
                                                                                                    <td>{{ ec.credit }}
                                                                                                        crédits</td>
                                                                                                </tr>
                                                                                            {% endif %}
                                                                                            {% endfor %}
                                                                                        </tbody>
                                                                                    {% endfor %}
                                                                                </table>
                                                                            </div>
                                                                        {% endfor %}

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
{% endblock %}

templates/uc/repartition_uc_by_niveau_pdf.html.twig
{% extends "base_pdf.html.twig" %}
{% block config %}
    <div id="root" layout="portrait" size="A4">
    {% endblock %}

    {% block return_top %}
        <a href="{{path('repartition_uc_by_niveau',{'type':parcour.id,'niveau':n})}}" id="button_generate" class="btn btn-danger">
            <i class="glyphicon glyphicon-arrow-left"></i>
            Retourner à la liste</a>
    {% endblock %}

    {% block return_bottom %}
        <a href="{{path('repartition_uc_by_niveau',{'type':parcour.id,'niveau':n})}}" id="button_generate" class="btn btn-danger">
            <i class="glyphicon glyphicon-arrow-left"></i>
            Retourner à la liste</a>
    {% endblock %}

    {% block custom_style %}
        <style type="text/css">
           tr {
               height : 1px;
           }
           td,th
           {
               font-size : 0.9em
           }
        </style>
    {% endblock %}

    {% block tete %}{% endblock %}

    {% block body %}
        <h4 class="text-center">
            <strong>Répartitions des UE et EC académique
                {{ niv_name.nom }}</strong>
            <span>({{parcour.type}})</span>
        </h4>
        <div>
        {% for sem in semestre %}
            <div class="col-xs-6" id="my_tableau">
                <h4 class="text-center">{{ sem.semestre }}</h3>
                <table class="table table-bordered">
                    {% for ue in sem.uEs %}
                        <thead class="col-sm-offset-8">
                            <tr>
                                <th>{{ue.nom}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ec in ue.ecs %}
                                <tr>
                                    <td>{{ ec.nom }}</td>
                                    <td>{{ ec.code }}</td>
                                    <td>{{ ec.credit }}
                                        crédits</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        {% endfor %}
        </div>
    {% endblock %}

    {% block script_function %}
        <script>
            function test() {
                var element = document.getElementById('content');
                html2pdf().from(element).set({
                    margin: 0.1,
                    filename: 'test.pdf',
                    html2canvas: {
                        scale: 5
                    },
                    jsPDF: {
                        orientation: 'landscape',
                        unit: 'in',
                        format: 'letter',
                        compressPDF: false
                    }
                }).save();
            }
        </script>
    {% endblock %}

    {% block footer_pdf %}{% endblock %}