src/Entity/FicheIndividuel.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FicheIndividuelRepository")
 * @ORM\Table(name="fiche_individuel")
 */
class FicheIndividuel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etudiant", inversedBy="ficheIndividuels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etudiant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EC", inversedBy="ficheIndividuels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $EC;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Semestre", inversedBy="ficheIndividuels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $semestre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AnneUniversitaire", inversedBy="ficheIndividuels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $anneUniversitaire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getEC(): ?EC
    {
        return $this->EC;
    }

    public function setEC(?EC $EC): self
    {
        $this->EC = $EC;

        return $this;
    }

    public function getSemestre(): ?Semestre
    {
        return $this->semestre;
    }

    public function setSemestre(?Semestre $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }

    public function getNote(): ?Note
    {
        return $this->note;
    }

    public function setNote(?Note $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getAnneUniversitaire(): ?AnneUniversitaire
    {
        return $this->anneUniversitaire;
    }

    public function setAnneUniversitaire(?AnneUniversitaire $anneUniversitaire): self
    {
        $this->anneUniversitaire = $anneUniversitaire;

        return $this;
    }
}

src/Entity/Note.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NoteRepository")
 * @ORM\Table(name="note")
 */
class Note
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etudiant", inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etudiant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EC", inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $EC;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Semestre", inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $semestre;

    /**
     * @ORM\Column(type="float")
     */
    private $valeur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isRatrapage;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AnneUniversitaire", inversedBy="notes")
     */
    private $anneUniversitaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Niveaux", inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $niveaux;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isValide;

    /**
     * @ORM\Column(type="float")
     */
    private $value_coeff;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NoteUc", inversedBy="notes")
     */
    private $note_uc;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_final;

    public function __construct()
    {
        $this->ficheIndividuels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getEC(): ?EC
    {
        return $this->EC;
    }

    public function setEC(?EC $EC): self
    {
        $this->EC = $EC;

        return $this;
    }

    public function getSemestre(): ?Semestre
    {
        return $this->semestre;
    }

    public function setSemestre(?Semestre $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }

    public function getValeur(): ?float
    {
        return $this->valeur;
    }

    public function setValeur(float $valeur): self
    {
        $this->valeur = $valeur;

        return $this;
    }

    public function getIsRatrapage(): ?bool
    {
        return $this->isRatrapage;
    }

    public function setIsRatrapage(bool $isRatrapage): self
    {
        $this->isRatrapage = $isRatrapage;

        return $this;
    }

    public function getAnneUniversitaire(): ?AnneUniversitaire
    {
        return $this->anneUniversitaire;
    }

    public function setAnneUniversitaire(?AnneUniversitaire $anneUniversitaire): self
    {
        $this->anneUniversitaire = $anneUniversitaire;

        return $this;
    }

    /**
     * @return Collection|FicheIndividuel[]
     */
    public function getFicheIndividuels(): Collection
    {
        return $this->ficheIndividuels;
    }

    public function addFicheIndividuel(FicheIndividuel $ficheIndividuel): self
    {
        if (!$this->ficheIndividuels->contains($ficheIndividuel)) {
            $this->ficheIndividuels[] = $ficheIndividuel;
            $ficheIndividuel->setNote($this);
        }

        return $this;
    }

    public function removeFicheIndividuel(FicheIndividuel $ficheIndividuel): self
    {
        if ($this->ficheIndividuels->contains($ficheIndividuel)) {
            $this->ficheIndividuels->removeElement($ficheIndividuel);
            // set the owning side to null (unless already changed)
            if ($ficheIndividuel->getNote() === $this) {
                $ficheIndividuel->setNote(null);
            }
        }

        return $this;
    }

    public function getNiveaux(): ?Niveaux
    {
        return $this->niveaux;
    }

    public function setNiveaux(?Niveaux $niveaux): self
    {
        $this->niveaux = $niveaux;

        return $this;
    }

    public function getIsValide(): ?bool
    {
        return $this->isValide;
    }

    public function setIsValide(bool $isValide): self
    {
        $this->isValide = $isValide;

        return $this;
    }

    public function getValueCoeff(): ?float
    {
        return $this->value_coeff;
    }

    public function setValueCoeff(float $value_coeff): self
    {
        $this->value_coeff = $value_coeff;

        return $this;
    }

    public function getNoteUc(): ?NoteUc
    {
        return $this->note_uc;
    }

    public function setNoteUc(?NoteUc $note_uc): self
    {
        $this->note_uc = $note_uc;

        return $this;
    }

    public function getIsFinal(): ?bool
    {
        return $this->is_final;
    }

    public function setIsFinal(bool $is_final): self
    {
        $this->is_final = $is_final;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"username"}, message="La pseudo est déja utiliser par un autre utilisateur")
 * @ORM\Table(name="acces")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Ce champ ne peut pas être vide")
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LoginType", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Etudiant", mappedBy="login", cascade={"persist", "remove"})
     */
    private $etudiant;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Enseignant", mappedBy="login", cascade={"persist", "remove"})
     */
    private $enseignant;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Information", mappedBy="user")
     */
    private $informations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\InformationChild", mappedBy="user")
     */
    private $informationChildren;

    public function __construct()
    {
        $this->informations = new ArrayCollection();
        $this->informationChildren = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getType(): ?LoginType
    {
        return $this->type;
    }

    public function setType(?LoginType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        // set (or unset) the owning side of the relation if necessary
        $newLogin = $etudiant === null ? null : $this;
        if ($newLogin !== $etudiant->getLogin()) {
            $etudiant->setLogin($newLogin);
        }

        return $this;
    }

    public function getEnseignant(): ?Enseignant
    {
        return $this->enseignant;
    }

    public function setEnseignant(?Enseignant $enseignant): self
    {
        $this->enseignant = $enseignant;

        // set (or unset) the owning side of the relation if necessary
        $newLogin = $enseignant === null ? null : $this;
        if ($newLogin !== $enseignant->getLogin()) {
            $enseignant->setLogin($newLogin);
        }

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Information[]
     */
    public function getInformations(): Collection
    {
        return $this->informations;
    }

    public function addInformation(Information $information): self
    {
        if (!$this->informations->contains($information)) {
            $this->informations[] = $information;
            $information->setUser($this);
        }

        return $this;
    }

    public function removeInformation(Information $information): self
    {
        if ($this->informations->contains($information)) {
            $this->informations->removeElement($information);
            // set the owning side to null (unless already changed)
            if ($information->getUser() === $this) {
                $information->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|InformationChild[]
     */
    public function getInformationChildren(): Collection
    {
        return $this->informationChildren;
    }

    public function addInformationChild(InformationChild $informationChild): self
    {
        if (!$this->informationChildren->contains($informationChild)) {
            $this->informationChildren[] = $informationChild;
            $informationChild->setUser($this);
        }

        return $this;
    }

    public function removeInformationChild(InformationChild $informationChild): self
    {
        if ($this->informationChildren->contains($informationChild)) {
            $this->informationChildren->removeElement($informationChild);
            // set the owning side to null (unless already changed)
            if ($informationChild->getUser() === $this) {
                $informationChild->setUser(null);
            }
        }

        return $this;
    }
}

templates/fiche_individuel/fiche_de_note_pdf.html.twig
{% extends "base_pdf.html.twig" %}
{% block config %}
    <div id="root" size="A4">
    {% endblock %}

    {% block return_top %}
        <a href="{{path('fiche_note',{'etudiant':e ,'niveaux':n,'semestre':s,'ratrapage':r})}}" id="button_generate" class="btn btn-danger">
            <i class="glyphicon glyphicon-arrow-left"></i>
            Retourner à la liste</a>
    {% endblock %}

    {% block return_bottom %}
        <a href="{{path('fiche_note',{'etudiant':e ,'niveaux':n,'semestre':s,'ratrapage':r})}}" id="button_generate" class="btn btn-danger">
            <i class="glyphicon glyphicon-arrow-left"></i>
            Retourner à la liste</a>
    {% endblock %}

    {% block custom_style %}
        <style type="text/css">
            .margin-left-4 {
                margin-left: 0.4cm;
                margin-top: 0.5cm;
            }
            /* tr {
               height : 1px;
           } */
            td,
            th {
                font-size: 0.8em
            }
            .tableb {
                margin-left: 0.4cm;
                margin-right: 0.4cm;
                width: 20.2cm;
            }
            .header {
                font-size: 0.8em;
            }
            .marg-top {
                margin-top: 0.1cm;
            }
            .list-group-item {
                position: relative;
                display: block;
                padding: 1px 5px;
                margin-bottom: -1px;
                background-color: #fff;
                border: 1px solid #ddd;
            }
            p {
                margin: 0 0 1px;
            }
        </style>
    {% endblock %}

    {% block tete %}
        <div class="header margin-left-4">
            <div class="col-md-5 ">
                <p class="text-center">Université d'Antananarivo</p>
                <p class="text-center">Ecole Supérieure Polytechnique</p>
                <p>Domaine : Sciences de l'ingénieur
                </p>
                <p>Mention : Electronique
                </p>
                <p>Parcours : Electronique et commande
                </p>
                <p>Niveau :
                    {{ etudiant.niveaux.nom }}
                </p>
            </div>
            <div class="col-md-4 col-md-offset-2">
                <p>Année Universitaire
                    {{ etudiant.anneUniversitaire.anneUniversitaire }}</p>
                <p>Semestre
                    <strong>{{ etudiant.niveaux.semestres['0'].nom }}</strong>
                </p>
                <p></p>
            </div>
        </div>
    {% endblock %}

    {% block body %}
        <div class="tableb">
            <ul class="list-group list-group-unbordered col-md-8 haeder">
                <h4 style="font-size:0.8em">
                    <strong>Relevé de notes par EC et UE et résultats du semestre</strong>
                </h4>
                <li class="list-group-item">
                    <b style="font-size:0.8em">Nom et prénom(s)</b>
                    <p class="pull-right" style="font-size:0.8em">{{etudiant.nom}}
                        {{etudiant.prenom}}</p>
                </li>
                <li class="list-group-item">
                    <b style="font-size:0.8em">Date de naissance</b>
                    <p class="pull-right" style="font-size:0.8em">
                        {{ etudiant.dateNaissance | date('d/m/Y')  }}</p>
                </li>
                <li class="list-group-item">
                    <b style="font-size:0.8em">Numéro d'inscription</b>
                    <p class="pull-right" style="font-size:0.8em">{% if scolarite != null %}{{scolarite.numeroInscription}}{% endif %}</p>
                </li>
            </ul>
            {%  for n_ue in note_ue %}
                <table class="col-md-12 table-bordered tablec marg-top" id="example1">
                    <thead>
                        <tr>
                            <th>Eléments constitutifs de l'UE
                                {{n_ue.uc.nom}}</th>
                            <th>Coeff</th>
                            <th>Note/20</th>
                            <th>Note*coeff</th>
                            <th>Crédits</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for note in n_ue.notes %}
                            {% if note.isFinal == 1 %}
                                <tr>
                                    <td>{{ note.EC.nom }}</td>
                                    <td>{{ note.EC.coefficient | number_format(2,'.','') }}</td>
                                    <td>{{ note.valeur | number_format(2,'.','') }}</td>
                                    <td>{{ note.valueCoeff | number_format(2,'.','') }}</td>
                                    <td>{{ note.EC.credit }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Total</th>
                            <th>{{ n_ue.uc.coefficient | number_format(2,'.','')}}</th>
                            <th></th>
                            <th>{{n_ue.valueCoeff | number_format(2,'.','')}}</th>
                            <th>{{n_ue.credit}}</th>
                        </tr>
                        <tr>
                            <th>Résultat</th>
                            <th></th>
                            <th>
                                {% if n_ue.valueCoeff > 10 %}Acquis{% else %}Ajourné
                                {% endif %}
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            {% endfor %}
        </div>
        <div class="col-md-3" style="width:10cm">
            <table class="table-bordered">
                 <tr>
                    <th>Moyenne Semestrielle</th>
                    {% if moyenne != null %}
                    <th>{{ moyenne.value | number_format(2,'.','') }}
                        /20</th>
                    {% else %}
                        <th>0
                        /20</th>
                    {% endif %}
                </tr>
                <tr>
                    <th>Crédit Acquis</th>
                    {% if moyenne != null %}
                    <th>{{ moyenne.credit }}
                        /30</th>
                    {% else %}
                        <th>0
                        /30</th>
                    {% endif %}
                </tr>
            </table>
        </div>
    {% endblock %}

    {% block script_function %}
        <script>
            function test() {
                var element = document.getElementById('content');
                html2pdf().from(element).set({
                    margin: 0.1,
                    filename: 'test.pdf',
                    html2canvas: {
                        scale: 5
                    },
                    jsPDF: {
                        orientation: 'portrait',
                        unit: 'in',
                        format: 'letter',
                        compressPDF: false
                    }
                }).save();
            }
        </script>
    {% endblock %}

    {% block footer_pdf %}{% endblock %}

templates/fiche_individuel/result.html.twig
{% for note in invalideNote %}
    <tr>
        <td>{{ note.EC.UC.nom }}</td>
        <td>{{ note.EC.nom }} ({{ note.valeur }})</td>
    </tr>
{% endfor %}